### ISSUE TITLE
10 questions for basic sas knowledge

### ISSUE THREAD

**Issue by kieranjmartin** [RConsortium/R-Certification-WG#16]
packages to read SAS, SAS formats, properties (label/character length, formats)

**Comment by joseph-ProCogia** [comment]
@kieranjmartin 

qn5: SAS only has character and numeric as types? Date/Time is stored as numeric. DCBS seems to be Asian specific with extensions. Havent seen that before. 

qn6: Missing last option?

qn7: Would add (" ") to correct answer as well

**Comment by kieranjmartin** [comment]
I have now updated this to address your points, and add another incorrect answer to each one
